tourist_attraction = {
  'Brasil': [
    {
      'id': 0,
      'name': 'Parque da Cidade',
      'desc': 'O Parque da Cidade de Brasília é um dos maiores parques urbanos do mundo e o maior da América Latina. Ele é um dos principais passeios em Brasília tanto para os moradores como para quem visita a cidade.',
      'image': 'http://www.turismo.df.gov.br/wp-conteudo/uploads/2017/12/PLA_3548-1679x1080.jpg',
      'characteristics': {1: 2, 2: 3, 3: 1},
    }, 
    {
      'id': 1,
      'name': 'Pontão do Lago Sul',
      'desc': 'Para quem vive ou visita Brasília, o Pontão do Lago Sul é local obrigatório. Atrativos não faltam ao maior centro de lazer e entretenimento da capital federal: cenário de cartão-postal, gastronomia variada, programação cultural e esportiva, amplo estacionamento e inúmeros serviços, além do seu clima quase praiano e do pôr-do-sol mais belo da cidade.',
      'image': 'https://www.pontao.com.br/arquivos/pontao-do-lago-sul-3-486130.jpg',
      'characteristics': {1: 3, 2: 2, 3: 1},
    },
    {
      'id': 2,
      'name': 'Museu Nacional da República',
      'desc': 'O Museu Nacional é integrante do Conjunto Cultural da República. É um espaço que insere Brasília no circuito internacional das artes e mostra o que há de melhor na arte brasileira. O espaço é utilizado para exposições itinerantes de artistas renomados e temas importantes para a sociedade, palestras, mostra de filmes, seminários e eventos importantes.',
      'image': 'https://alo.com.br/wp-content/uploads/2019/11/Nota-1-divulgacao-3.jpg',
      'characteristics': {1: 3, 2: 2, 3: 1},
    },
  ],
  'Argentina': [
    {
      'id': 3,
      'name': 'Casa Rosada',
      'desc': 'Casa Rosada é a sede da presidência da República Argentina, em Buenos Aires, assim chamada pela cor aproximadamente rosa. Abriga também o Museu da Casa do Governo, com material relacionado aos presidentes do país.',
      'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Casa_Rosada_exterior_from_Plaza_de_Mayo.JPG/1920px-Casa_Rosada_exterior_from_Plaza_de_Mayo.JPG',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 4,
      'name': 'Caminito',
      'desc': 'O Caminito é um dos passeios mais emblemáticos da Cidade e dos atrativos imperdíveis para os que o visitam. No bairro de La Boca, os “conventillos” (cortiços) típicos com paredes de zinco pintadas de várias cores, contam a história de uma época em que as famílias originais fugiram da região por conta da epidemia de tifo, mudando-se para a parte alta da cidade, deixando suas mansões quase abandonadas, alugadas para os imigrantes que desembarcavam no porto.',
      'image': 'https://aguiarbuenosaires.com/wp-content/uploads/2018/07/caminito.jpg',
      'characteristics': {1: 3, 2: 1, 3: 2},
    },
    {
      'id': 5,
      'name': 'Ecoparque',
      'desc': 'O antigo Zoológico de Buenos Aires está sendo transformado num Ecoparque interativo, educativo e ambiental, seguindo as tendências do século XXI. Visitá-lo em família é fazer parte de um processo de transformação que visa melhorar a qualidade de vida dos animais.',
      'image': 'https://turismo.buenosaires.gob.ar/sites/turismo/files/_ecoparque1_1500x610.jpg',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
  ],
  'Uruguai': [
    {
      'id': 6,
      'name': 'Punta Carretas',
      'desc': 'O bairro costeiro chique de Punta Carretas inclui o Faro de Punta Brava, um farol de 1870 com vista para o mar. Na Rambla Gandhi, um famoso calçadão na orla, é possível encontrar restaurantes casuais e praias rochosas. ',
      'image': 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Punta_Carretas_skyline.jpg',
      'characteristics': {1: 3, 2: 2, 3: 1},
    },
    {
      'id': 7,
      'name': 'Teatro Solis',
      'desc': 'O Teatro Solís da cidade de Montevidéu foi inaugurado no ano de 1856 na presença do presidente Gabriel Antonio Pereira, com a representação da ópera Ernani de Giuseppe Verdi, embora a ideia de ter um teatro de nível internacional na capital da jovem república quase sempre existiu',
      'image': 'https://c9h6z5c4.stackpathcdn.com/wp-content/uploads/2018/08/teatro-solis-montevideu.png',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 8,
      'name': 'Praia De los Pocitos',
      'desc': 'A Playa de los Pocitos está localizada em uma área mais residencial e é bastante frequentada por moradores da região, além dos turistas, durante o calor em Montevidéu. Ao redor, no bairro de Pocitos, estão diversos comércios e restaurantes que costumam lotar nos devido ao movimento da praia.',
      'image': 'https://c9h6z5c4.stackpathcdn.com/wp-content/uploads/2018/07/praias-em-montevideu-playa-pocitos-uruguai.png',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
  ],
  'Chile': [
    {
      'id': 9,
      'name': 'Barrio Lastarria',
      'desc': 'Um bairro considerado um oásis escondido em meio ao centro da cidade. O Lindo Barrio Lastarria pode ser uma boa opção para quem apenas conhecer um lindo lugar, comer em um belo restaurante e/ou se hospedar em um bairro lindo e central',
      'image': 'https://i0.wp.com/santiagodochile.com/wp-content/uploads/Barrio-Lastarria.jpg',
      'characteristics': {1: 3, 2: 1, 3: 2},
    },
    {
      'id': 10,
      'name': 'Museu Chileno de Arte Pré-Colombiana',
      'desc': 'O Museu Chileno de Arte Pré-colombiana é um museu de arte dedicado ao estudo e exibição de obras de arte e artefatos pré-colombianos da América do Sul e Central. O museu está localizado no centro da cidade de Santiago, capital do Chile.',
      'image': 'https://media-cdn.tripadvisor.com/media/photo-s/0b/98/c8/e6/muestra-mapuche.jpg',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 11,
      'name': 'Cerro San Cristóbal',
      'desc': 'O Cerro San Cristóbal encontra-se no coração da zona urbana de Santiago do Chile e é parte do maior parque urbano da cidade, O Parque Metropolitano. No topo do cerro encontram-se várias terraças amplas, assim como mirantes de onde se pode apreciar a amplitude da capital em meio à vegetação e paz do lugar.',
      'image': 'https://i0.wp.com/santiagodochile.com/wp-content/uploads/Santiago-O-Cerro-San-Cristobal.jpg',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
  ],
  'Paraguai': [
    {
      'id': 12,
      'name': 'Panteão Nacional dos Heróis',
      'desc': 'O Panteão Nacional dos Heróis é um monumento localizado em Assunção, capital do Paraguai. Construído originalmente como templo católico, o edifício atualmente cumpre funções religiosas, protocolares e de homenagem a personagens da história e cultura paraguaias',
      'image': 'https://st2.depositphotos.com/1723045/43759/i/600/depositphotos_437596280-stock-photo-national-pantheon-of-the-heroes.jpg',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 13,
      'name': 'Jardim Botânico e Zoológico de Assunção',
      'desc': 'O Jardim Botânico e Zoológico de Assunção é um jardim botânico e zoológico localizado em Assunção, capital da República do Paraguai. O Jardim Botânico e Zoológico é um dos principais espaços abertos da cidade de Assunção, inserido em um bosque natural de 110 hectares ao norte da cidade.',
      'image': 'https://www.parlamentomercosur.org/innovaportal/file/17080/1/jardim-botanico-asuncion-pq.jpg',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
    {
      'id': 14,
      'name': 'Avenida e Praia Costanera',
      'desc': 'A Avenida Costanera é uma das vias mais extensas da cidade, mas a sua parte mais famosa é a que margeia a Baía de Assunção. Foi inaugurada em 2012, e desde então se tornou um dos melhores pontos de passeio e lazer da cidade.',
      'image': 'https://ficaativoeviaja.com.br/wp-content/uploads/2020/04/6889-Costanera-de-Asuncion.avif',
      'characteristics': {1: 3, 2: 2, 3: 1},
    },
  ],
  'Bolivia': [
    {
      'id': 15,
      'name': 'Teleférico',
      'desc': 'Uma das grandes atrações de La Paz é o sistema de transporte público feito por teleféricos – o Mi Teleférico. Com início de operação em 2014, a rede de teleféricos da capital boliviana se tornou a maior do mundo. Até 2016, o sistema consistia de três linhas e 11 estações de embarque e desembarque.',
      'image': 'https://www.viagensecaminhos.com/wp-content/uploads/2018/11/mi-teleferico-la-paz.jpg',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
    {
      'id': 16,
      'name': 'Mercado das Bruxas',
      'desc': 'O Mercado das Bruxas, também conhecido como El Mercado de las Brujas e La Hechiceria, é uma atração turística popular localizada em Cerro Cumbre, uma clareira em La Paz, Bolívia.',
      'image': 'https://cdnstatic8.com/viajandonajanela.com/wp-content/uploads/2018/10/mercado-das-bruxas-la-paz-viajando-na-janela-1-de-14.jpg?ssl=1',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 17,
      'name': 'Luta livre de Cholitas',
      'desc': 'É em La Paz, ou melhor, na cidade satélite vizinha El Alto, que acontece a Luta Livre de Cholitas. Trata-se de um espetáculo onde as “Cholitas” se enfrentam em uma espécie de luta teatral, como o bom e velho conhecido “telecacth”. É no Cholitas Wrestling que as cholitas mostram força e acrobacias em um espetáculo ímpar!',
      'image': 'https://emalgumlugardomundo.com.br/wp-content/uploads/2018/08/luta-livre-de-cholitas-74.jpg',
      'characteristics': {1: 3, 2: 1, 3: 2},
    },
  ],
  'Peru': [
    {
      'id': 18,
      'name': 'Huaca Pucllana',
      'desc': 'Huaca Pucllana é um sítio arqueológico pertencente à cultura Lima, do período de desenvolvimentos regionais, localizado no distrito de Miraflores, província de Lima, no Peru.',
      'image': 'https://www.peruhop.com/wp-content/uploads/Pucllana-Temple2.jpg',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 19,
      'name': 'Parque da Reserva',
      'desc': 'O Parque da Reserva é um dos lugares mais surpreendentes de Lima. Não importa a idade ou a companhia, caminhar pelo lugar é como retornar à infância e sentir-se criança outra vez. O parque possui diversas fontes aquáticas, cada uma com uma iluminação especial, provocando um belo espetáculo aos olhos como resultado final. Há fontes de diversas cores e de diferentes formas ao longo da noite, sempre com o poder de encantar os visitantes. ',
      'image': 'https://spguia.melhoresdestinos.com.br/system/fotos_local/fotos/3311/show/parque-da-reserva.jpg',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
    {
      'id': 20,
      'name': 'Barranco',
      'desc': 'Barranco, em Lima, é um dos distritos mais tradicionais da cidade e um dos mais charmosos também. Por lá, encontrei uma mistura gostosa de arte e boemia pelas ruas. Música e artistas locais espalhados por todo canto, o que me deixou com aquele sentimento de ‘encanto à primeira vista’.',
      'image': 'https://www.thetinytravelogue.com/wp-content/uploads/2018/05/P4014366-1596x860.jpg',
      'characteristics': {1: 3, 2: 1, 3: 2},
    },
  ],
  'Colombia': [
    {
      'id': 21,
      'name': 'Jardim Botânico de Bogotá',
      'desc': 'O jardim botânico José Celestino Mutis é o maior jardim botânico da Colômbia. Serve como centro de recreação e pesquisa, com ênfase nos ecossistemas andino e Páramo.',
      'image': 'https://images.adsttc.com/media/images/6080/e328/f91c/818c/1000/0119/newsletter/DJI_0106.jpg?1619059486',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
    {
      'id': 22,
      'name': 'Museu do Ouro',
      'desc': 'O Museu do Ouro de Bogotá, considerado um dos maiores museus de ouro do mundo, e um dos principais, localiza-se na capital colombiana.',
      'image': 'https://b9g6i2e6.stackpathcdn.com/wp-content/uploads/2018/12/museu-do-ouro-bogota.jpg',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 23,
      'name': 'Morro de Monserrate',
      'desc': 'O morro de Monserrate é o mais conhecido dos cerros Orientais de Bogotá. Junto a Guadalupe é um dos morros tutelares da cidade. Monserrate tem uma altitude de 3152 m e localiza-se sobre a cordillera oriental.',
      'image': 'https://www.viagensecaminhos.com/wp-content/uploads/2019/03/teleferico-monserrate-bogota.jpg',
      'characteristics': {1: 3, 2: 2, 3: 1},
    },
  ],
  'Venezuela': [
    {
      'id': 24,
      'name': 'Parque Nacional El Ávila',
      'desc': 'O Parque Nacional de Ávila, oficialmente conhecido como Parque Nacional Waraira Repano por seu nome indígena Cariban, protege parte da cordilheira Cordilheira da Costa Central, na região costeira do centro-norte da Venezuela. A elevação mais alta da área é Pico Naiguatá, a 2.765 metros acima do nível do mar.',
      'image': 'https://www.viagensecaminhos.com/wp-content/uploads/2019/03/teleferico-monserrate-bogota.jpg',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
    {
      'id': 25,
      'name': 'Museu de Belas Artes de Caracas',
      'desc': 'O Museu de Belas Artes de Caracas é o mais antigo e um dos mais importantes museus de arte da Venezuela. Fundado em 1917, é uma instituição pública federal, subordinada à Fundação Museus Nacionais',
      'image': 'https://upload.wikimedia.org/wikipedia/commons/8/8f/MBA_2014.jpg',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 26,
      'name': 'Centro Cultural Bod',
      'desc': 'Centro Cultural BOD é um dos lugares favoritos dos amantes da cultura na capital de Venezuela. É o centro de entretenimento de um banco bem conhecido no país e é um lugar onde fazem diferentes apresentações, como peças de teatro e concertos.',
      'image': 'https://runrun.es/wp-content/uploads/2015/07/centro-cultural-bod1.jpg',
      'characteristics': {1: 3, 2: 1, 3: 2},
    },

  ],
  'Guiana': [{
    {
      'id': 27,
      'name': 'Promenade Gardens',
      'desc': 'Promenade Gardens é um jardim em Georgetown, Guiana. Ao sul fica o Parque da Independência, local de execução pública dos escravos que participaram do levante de 1823. O parque é separado dos jardins pela Rua do Meio. O parque é limitado pela Rua Carmichael a oeste, em frente à qual fica a State House.',
      'image': 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/e2/53/6f/feature.jpg?w=1200&h=-1&s=1',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
    {
      'id': 28,
      'name': "St George's Cathedral",
      'desc': 'A Igreja Catedral Metropolitana de St George, geralmente conhecida como Catedral de St George, Southwark é a catedral da Arquidiocese Católica Romana de Southwark, sul de Londres e é a sede do Arcebispo de Southwark',
      'image': 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/e7/39/f7/photo0jpg.jpg?w=1200&h=-1&s=1',
      'characteristics': {1: 1, 2: 2, 3: 3},
    },
    {
      'id': 29,
      'name': "The Georgetown Lighthouse",
      'desc': 'O Farol de Georgetown foi construído pela primeira vez pelos holandeses em 1817 e depois reconstruído em 1830 para ajudar a guiar os navios do Oceano Atlântico para o rio Demerara.',
      'image': 'https://upload.wikimedia.org/wikipedia/commons/3/39/Georgetown-Lighthouse.jpg',
      'characteristics': {1: 3, 2: 2, 3: 1},
    },
  }],
  'Suriname': [
    {
      'id': 30,
      'name': "Palmentuin",
      'desc': 'Jardim das Palmeiras ou Palmgardens é uma palmeira de paisagem de jardim em Paramaribo, Suriname. Além de altura palmeira-imperial, os motivos são o lar de aves tropicais e uma "tropa" de macacos-prego. Palmentuin está localizado na Van Roseveltkade atrás do Palácio Presidencial do Suriname e é uma atração turística.',
      'image': 'https://9968c6ef49dc043599a5-e151928c3d69a5a4a2d07a8bf3efa90a.ssl.cf2.rackcdn.com/1166100.jpg',
      'characteristics': {1: 2, 2: 1, 3: 3},
    },
    {
      'id': 31,
      'name': "Fort Zeelandia",
      'desc': 'A fortificação foi erguida no início do século XVII na margem esquerda do rio Suriname, com a função de defesa de um entreposto comercial fronteiriço Neerlandês próximo à aldeia indígena de Parmurbo, posteriormente denominada de Paramaribo.',
      'image': 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/3a/4a/d0/fort-zeelandia.jpg?w=1200&h=-1&s=1',
      'characteristics': {1: 2, 2: 1, 3: 3},
    },
    {
      'id': 32,
      'name': "Paramaribo Zoo",
      'desc': 'O Zoológico de Paramaribo é o único zoológico do Suriname. O zoológico foi inaugurado em maio de 1972 e foi uma iniciativa do primeiro-ministro Jopie Pengel. Ele está localizado ao lado do Cultuurtuin em Rainville, Paramaribo.',
      'image': 'https://paramaribozoosuriname.sr/wp-content/uploads/2021/03/CC9483C2-FB72-4F47-8299-DED1FFF370FA-2.jpg',
      'characteristics': {1: 3, 2: 2, 3: 1},
    },
  ],
  'Guiana Francesa': [
    {
      'id': 33,
      'name': "Parque Guiana Amazonian",
      'desc': 'O Parque Amazônico da Guiana é o maior Parque Nacional da França, com o objetivo de proteger parte da floresta amazônica localizada na Guiana Francesa que cobre 41% da região. É o maior parque da França, na União Europeia, e um dos maiores parques nacionais do mundo.',
      'image': 'https://lacgeo.com/sites/default/files/french_guiana_tropical_forest_towards_cacao_opt%20%281%29.jpg',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
    {
      'id': 34,
      'name': "Fort Diamant",
      'desc': 'O Fort Diamant localiza-se em Caiena, na ilha de mesmo nome, na comuna de Rémire Montjoly, na Guiana Francesa.',
      'image': 'http://www.alluringworld.com/wp-content/uploads/2019/10/1-Fort-Diamant-700x440.jpg',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 35,
      'name': "Kourou Space Centre",
      'desc': 'O Centro Espacial da Guiana é uma base de lançamento espacial ou espaçoporto francês e da ESA ao noroeste de Kourou, na Guiana Francesa. Em operação desde 1968, é particularmente adequado como local para uma base de lançamento espacial.',
      'image': 'https://cdn.mos.cms.futurecdn.net/QjA9BQ3GPDc29HiKTrJVL6.jpg',
      'characteristics': {1: 3, 2: 1, 3: 2},
    },
  ],
  'Equador': [
    {
      'id': 36,
      'name': "Laguna del Quilotoa",
      'desc': 'Quilotoa é um lago de cratera cheio de água e o vulcão mais ocidental dos Andes equatorianos. A caldeira de 3 quilômetros de largura foi formada pelo colapso deste vulcão dacito após uma erupção',
      'image': 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/20/e7/0b/quilatoa-and-wild-flowers.jpg?w=1200&h=-1&s=1',
      'characteristics': {1: 2, 2: 3, 3: 1},
    },
    {
      'id': 37,
      'name': "Centro Histórico de Quito",
      'desc': 'O centro histórico de Quito encontra-se no centro sul da cidade de Quito, no Equador, em uma área de 3,75 km², e é considerado o conjunto histórico mais bem conservado e um dos mais importantes de América Latina.',
      'image': 'https://www.melevaviajar.com.br/wp-content/uploads/2017/05/Centro-Hist%C3%B3rico-de-Quito-5.jpg',
      'characteristics': {1: 1, 2: 3, 3: 2},
    },
    {
      'id': 38,
      'name': "Bairro La Mariscal",
      'desc': 'Este charmoso bairro concentra a vida noturna da cidade. Lá estão os bares, os restaurantes e as baladas da moda. É o local perfeito para curtir a noite na cidade. Está localizado a cerca de quatro quilômetros do Centro histórico.',
      'image': 'https://thumbs.dreamstime.com/b/plaza-foch-no-distrito-mariscal-em-quito-equador-do-turista-do-la-44994645.jpg',
      'characteristics': {1: 3, 2: 1, 3: 2},
    },
  ],
}